name: EnvMapper Tests

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        source-url: https://api.nuget.org/v3/index.json

    - name: 'Restore packages'
      run: dotnet restore

    - name: 'Build project'
      run: dotnet build --no-restore --configuration Release

    - name: 'Test'
      run: dotnet build --no-restore --configuration Release
